services:
  - type: web
    name: pdfhelper-backend
    runtime: python3.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: UPLOAD_DIR
        value: uploaded_pdfs

  - type: web
    name: pdfhelper-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NEXT_PUBLIC_API_URL
        value: https://pdfhelper-backend.onrender.com # You'll need to update this with your actual backend URL 